import "./globals.css";
import Head from "next/head";

// Include Google Font link here
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      {/* Add Head component for SEO and external links */}
      <Head>
        {/* Preconnect to Google Fonts */}
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        {/* Link to Google Fonts */}
        <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;700&display=swap" rel="stylesheet" />
      </Head>
      <body className="font-roboto">
        {/* Include your children components */}
        {children}
      </body>
    </html>
  );
}
